name: FactionsLite
main: com.example.factionslite.FactionsLite
version: 1.2.0
api-version: '1.20'
author: You
commands:
  f:
    description: FactionsLite main command
    usage: /f help
    aliases: [faction, factions]
permissions:
  factionslite.user:
    default: true
  factionslite.admin:
    default: op
